### ISSUE TITLE
Suggestion: Have the three crates in the same repository

### ISSUE THREAD

**Issue by pedrocr** [parched/runtime-target-feature-rt-rs#3]
I've seen it done for other crates that you have a single repository with multiple crates in it. For example:

https://github.com/RustCrypto/utils/

It might make sense to do that with runtime-target-feature instead of having three repositories for a single feature. It's even possible to merge git histories to get a single unified repo that goes back to the start.

**Comment by parched** [comment]
That's a good idea, I'm not sure why I didn't think of that to start with.

**Comment by pedrocr** [comment]
`1 crate = 1 repository` is such a common pattern it's surprising to do something else I guess :)

**Comment by parched** [comment]
Done see https://github.com/parched/runtime-target-feature-rs
