### ISSUE TITLE
It should be possible to specify multiple feature combos

### ISSUE THREAD

**Issue by pedrocr** [parched/runtime-target-feature-rt-rs#4]
For some situations there may be several levels of optimization depending on features. Maybe AVX is already enough for some speedups and AVX2 gives something extra. It would be nice to have the macro allow setting multiple alternate versions beyond the base one.

**Comment by parched** [comment]
Yes, that's planned next after I fix features with dashs and dots in their names. See https://github.com/parched/runtime-target-feature-rs/issues/1. PS I'm going to close the repo because I have merged it with the other
