### ISSUE TITLE
As a convenience common multi-level optimizations setups could be defined

### ISSUE THREAD

**Issue by pedrocr** [parched/runtime-target-feature-rt-rs#5]
As a follow-up to #4 it would probably be nice to have a few convenience macros that encode common performance ladders used in several places. For example for SIMD there is a progression in features on x86 and probably a similar one on ARM. It would be nice if there was a convenience `#[simd_target_features]' or similar that would encode a reasonable performance ladder for both Intel and ARM so this doesn't need to be replicated poorly in a bunch of projects.

**Comment by parched** [comment]
Closing in favour of https://github.com/parched/runtime-target-feature-rs/issues/7
